version: "3"

services:
  database:
    restart: always
    build: ./postgres/
    container_name: "database"
    env_file: 
      - ./postgres/database.env
    ports: 
      - 5432:5432
  backend:
    build: .
    ports: 
      - 8080:8080
    container_name: "server"
    depends_on:
      - database